// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-AngDENc7J2UKETlQau7LUfrVphfMR6M',
    appId: '1:875468350917:web:6e2de97f001a625d4917ac',
    messagingSenderId: '875468350917',
    projectId: 'ai-taleem-app',
    authDomain: 'ai-taleem-app.firebaseapp.com',
    storageBucket: 'ai-taleem-app.firebasestorage.app',
    measurementId: 'G-E6F45VL9G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7KcAH1dsSho1fqEvZgsxI2DoMCdRIYeU',
    appId: '1:875468350917:android:0399e0debe8a8a924917ac',
    messagingSenderId: '875468350917',
    projectId: 'ai-taleem-app',
    storageBucket: 'ai-taleem-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfDxt5jWxTgKxFCMifGJk7q63SIpqCA6E',
    appId: '1:875468350917:ios:2026da75912341c44917ac',
    messagingSenderId: '875468350917',
    projectId: 'ai-taleem-app',
    storageBucket: 'ai-taleem-app.firebasestorage.app',
    iosBundleId: 'com.example.taleemAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfDxt5jWxTgKxFCMifGJk7q63SIpqCA6E',
    appId: '1:875468350917:ios:2026da75912341c44917ac',
    messagingSenderId: '875468350917',
    projectId: 'ai-taleem-app',
    storageBucket: 'ai-taleem-app.firebasestorage.app',
    iosBundleId: 'com.example.taleemAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-AngDENc7J2UKETlQau7LUfrVphfMR6M',
    appId: '1:875468350917:web:b266b53e482166b94917ac',
    messagingSenderId: '875468350917',
    projectId: 'ai-taleem-app',
    authDomain: 'ai-taleem-app.firebaseapp.com',
    storageBucket: 'ai-taleem-app.firebasestorage.app',
    measurementId: 'G-DL2JHJ70TH',
  );
}
